name: abide-hgnn
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pyg
  - torchmetrics
  - pip
  - nilearn
  - scikit-learn
  - networkx
  - numpy
  - pyyaml
  - plotly
  - bandit
  - flake8
  - mypy
  - pytest
  - matplotlib
  - pip:
      - dhg==0.9.5
      - kaleido